create table
  public.carts (
    cart_id bigint generated by default as identity,
    customer_name text null,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_item_id bigint generated by default as identity,
    quantity integer null default 0,
    catalog_id bigint not null,
    cart_id bigint null,
    constraint cart items_pkey primary key (cart_item_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id) on delete cascade,
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalogs (catalog_id)
  ) tablespace pg_default;

  create table
  public.catalogs (
    catalog_id bigint generated by default as identity,
    sku text null,
    inventory integer null,
    price integer null,
    red integer null,
    green integer null,
    blue integer null,
    dark integer null,
    constraint catalogs_pkey primary key (catalog_id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;